### ISSUE TITLE
Tuner frequency wrong in /nb.html page

### ISSUE THREAD

**Issue by pa3ang** [dj0abr/QO-100_SSB-WebSDR_DATV-WebSpectrum#4]
Hi Kurt,

Although entering my 70 cm RTL tuner frequency the calculation is not made. I have to enter the LNB_CRYSTAL frequency in qo100websdr.h to get the transponder visual and when i click in the waterfall to adjust the frequency it locks to 10737.418239 MHz fix.  Adusting in the lower part of the screen (the IF screen) the frequency jumps correct starting from 10489.250000 MHz.

Running RPi4, Firefox (tried also Edge).

Any idea.

73 Johan, PA3ANG

**Comment by dj0abr** [comment]
Hi Johan,
tnx for the QSO.

Please do the following:
* Change your GPSDO to the frequency: 25787179 Hz. Then you receive the CW beacon at 432,550 MHz
* download the actual version, the version of today has your LNB frequency already in qo100websdr.h
* compile with ./build_RTLSDR
* start with  sudo  ./qo100websdr

now look for the beacons. The RTLsdr usually has a big offset. My RTLsdr is 70kHz off frequency.
To compensate it go into qo100websdr.h and enter a value for RTL_TUNER_CORRECTION. Start with a low value i.e.: 10. Recompile and restart. Check if the beacon gets closer to the 10489,55. If not, then enter a negative number i.e.: -10. Change this value to get the beacon close to its position. If you are closer than 10 kHz the auto lock will do the rest and the beacon jumps to its correct frequency.

Then the mouse click should work as expected.
I think the problem was the GPSDO (LNB_CRYSTAL) frequency. If both, the GPS and the LNB_CRYSTAL is at the same and correct value then it should work as expected. I have tested it with my RTLsdr and above values.

vy 73,
Kurt, DJ0ABR

**Comment by pa3ang** [comment]
Hi Kurt,

---  Not sure if you received my answer yesterday ----
Thanks for you quick reply to the issue. but it's still the same.

Attached two files with the messages in the terminal session and what happens on the website. As soon as i click on the waterfall to adjust the tuning frequency it hops to 10737.423649 MHz.

Regards,
Johan

![terminal](https://user-images.githubusercontent.com/5455100/72850606-c88c5100-3ca9-11ea-98ba-cdcc1bd4c12b.JPG)
![website](https://user-images.githubusercontent.com/5455100/72850614-caeeab00-3ca9-11ea-91b9-6bc2a7076239.JPG)

**Comment by dj0abr** [comment]
Hi Johan,
the problem is fixed. It was a number overflow on the 32bit raspberry.
Now all should work as expected.
vy 73, Kurt, DJ0ABR

**Comment by pa3ang** [comment]
Hi Kurt, 

Thanks. The issues is solved and the program is working on a RPi. 

vy 73 Johan, PA3ANG

Kurt Moraw schreef op 2020-01-24 01:01:

> Closed #4 [1]. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].
 

Links:
------
[1]
https://github.com/dj0abr/QO-100_SSB-WebSDR_DATV-WebSpectrum/issues/4
[2]
https://github.com/dj0abr/QO-100_SSB-WebSDR_DATV-WebSpectrum/issues/4?email_source=notifications&amp;email_token=ABJTZ7EMIIW36JRKXCNHNGTQ7IVXLA5CNFSM4KIS4ZG2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOWFO2MSI#event-2975704649
[3]
